name: Main Branch Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vlindersoftware/validate-coverage

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test and Validate
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  build-dev:
    name: Build Development Image
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push development image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test development image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/examples:/workspace \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main \
            /workspace/clover.xml 80 clover

  ensure-latest-version:
    name: Ensure Main Uses Latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check and fix action.yml version
        run: |
          # Check if action.yml is using latest
          if grep -q "docker://ghcr.io/vlindersoftware/validate-coverage:latest" action.yml; then
            echo "✅ action.yml correctly uses latest tag"
          else
            echo "🔧 Updating action.yml to use latest tag"
            
            # Update to latest
            sed -i "s|docker://ghcr.io/vlindersoftware/validate-coverage:[^'\"]*|docker://ghcr.io/vlindersoftware/validate-coverage:latest|g" action.yml
            
            # Verify the change
            if grep -q "docker://ghcr.io/vlindersoftware/validate-coverage:latest" action.yml; then
              echo "✅ Successfully updated action.yml to use latest"
              
              # Commit the change
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              
              git add action.yml
              git commit -m "chore: Reset action.yml to use latest on main branch"
              git push
              
              echo "✅ Committed action.yml update"
            else
              echo "❌ Failed to update action.yml"
              exit 1
            fi
          fi
