name: Release Branch Validation

on:
  push:
    branches: [ 'release/v*' ]

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Test and Validate
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      
  validate-action:
    name: Validate Action Configuration
    uses: ./.github/workflows/validate-action.yml
    permissions:
      contents: read
